<html>

  <h1>Dear ${firstName},</h1>

  <p>You account is created on Gandhi Vichar Sanskar Pariksha, Gandhi Research Foundation exam management applications. Please use below details to login and activate your accounts. Thank you.</p>
  <p>Username: ${user.email_id}</p>
  <p>Password: ${user.password}</p>
  <p>Application URL: ${siteUrl}</p>
  
  <br>
  <p>Thanks and Regards</p>  
  <p>Gandhi Vichar Sanskar Pariksha,</p>
  <p>Gandhi Research Foundation,</p>
  <p>Gandhi Teerth, Jain Hills, Jalgaon, Maharashtra-425003</p>
  <p>website: http://www.gandhifoundation.net</p>

</html> 