angular.module("prostudyApp")
		.controller(
				"partnerSchoolAddCtr",
				function($scope, $window, $mdToast, $timeout, $mdSidenav,
						$mdUtil, $log, $q, tableTestDataFactory, $state,
						$stateParams, appEndpointSF, partnerSchoolLevels,
						standardList) {

					console.log("Inside partnerSchoolAddCtr");
					$scope.curUser = appEndpointSF.getLocalUserService()
							.getLoggedinUser();

					$scope.partnerSchoolLevels = partnerSchoolLevels;
					$scope.standardList = standardList;
					// ----------tab control-------
					$scope.max = 4;
					$scope.selectedIndex = 0;
					$scope.tabNext = function() {
						var index = ($scope.selectedIndex == $scope.max) ? $scope.selectedIndex
								: $scope.selectedIndex + 1;
						$scope.selectedIndex = index;

					}
					// ----------------------------

					// -------------language-------
					$scope.languages = [ "Hindi", "Marathi", "English" ];
					$scope.selected = [];
					$scope.toggle = function(item, list) {
						var idx = list.indexOf(item);
						if (idx > -1) {
							list.splice(idx, 1);
						} else {
							list.push(item);
						}
						/* $log.debug("=="+$scope.selected); //work fine */
					};
					$scope.exists = function(item, list) {
						return list.indexOf(item) > -1;

					};
					// ----------------------------
					// -----------online ofline------
					/*
					 * $scope.data = { $scope.modeOfExam = 'OffLine';
					 * $scope.bookRequired = 'OffLine'; };
					 */
					// ----------------------------
					// ---auto ganereted number
					// ------------------------
					$scope.partnerSchool = {
						address : $scope.Address,
						examDetailList : [],
						contactDetail : "",
						autoGenerated : "",
						govRegisterno : "",
						instituteID : "",
						schoolName : "",
						instName : "",
						formNumber : "",
						category : "",
						primaryContact : ""

					};
					$scope.examDetail = {
						totalStudent : "",
						male : "",
						female : "",
						total : "",
						/* examMedium : $scope.selected, */
						yearOfExam : "",
						bookRequired : 'OffLine',
						modeOfExam : 'OffLine',
						bookSummary : "",
						paymentDetail : $scope.PaymentDetail,

					}
					$scope.contactDetail = {
						headMasterName : "",
						headMasterMobile : "",
						headMasterPhone : "",
						headMasterEmailId : "",
						coordinatorDetail : [ {
							srno : 1,
							coordinatorName : "",
							coordinatorPhoneNum : "",
							coordinatorMobileNum : "",
							coordinatorEmailId : "",
						} ]

					}
					
					$scope.Address = {
						line1 : "",
						dist : "",
						city : "",
						state : "",
						country : "India",
						pin : "",
						tal : "",
						otherState :"",
						otherDist : "",
						otherTal : "",
						otherAddressFlag : false
					}

					$scope.bookSummary = {
						bookDetail : [ {
							standard : "",
							bookName : "",
							bookPrise : 0,
							totalStud : 0,
							totalFees : 0
						} ],
						total : 0,
						amtForInst20per : 0,
						amtForGRF80per : 0
					}

					// attached the bookdetail to book summery entity
					$scope.bookDetail = {
						standard : "",
						bookName : "",
						bookPrise : 0,
						totalStud : 0,
						totalFees : 0

					}

					$scope.PaymentDetail = {
						payReceivedBy : "",
						paymentDate : new Date(),
						payAmount : 0,
						note : "",
						tPaid : 0,
						pAmount : 0,
						nameOfBank : "",
						branchName : "",
						transactionNumber : "",
						depositDate : new Date(),

					}

					// get last next 3 year to show academic year
					$scope.getNextYears = function() {
						var date = new Date();
						for (var i = 0; i < 3; i++) {
							var year = date.getFullYear();
							year = year.toString().substr(2, 2);

							$scope.Years.push(date.getFullYear() + "-"
									+ (Number(year) + 1));
							date.setYear(date.getFullYear() + 1);
						}
					}

					$scope.Years = [];
					$scope.getNextYears();
					// ----get pre year to push years----
					$scope.getPrvYears = function() {
						var date = new Date();

						for (var i = 0; i < 3; i++) {
							var year = date.getFullYear();
							year = year.toString().substr(2, 2);

							$scope.Years.push((date.getFullYear() - 1) + "-"
									+ (Number(year)));
							date.setYear(date.getFullYear() - 1);
						}

					}
					$scope.getPrvYears();
					// ---get curyear ------
					$scope.getCurYear = function() {
						var date = new Date();
						var curyear = date.getFullYear();
						curyear = curyear.toString().substr(2, 2);
						$scope.yearOfExam = date.getFullYear() + "-"
								+ (Number(curyear) + 1);
					}
					$scope.getCurYear();

					$scope.calculateTotal = function() {
						$scope.examDetail.total = Number($scope.examDetail.male)
								+ Number($scope.examDetail.female);
					}

					$scope.selectedPSchoolId = $stateParams.selectedPSchoolId;
					$log.debug("$scope.selectedPSchoolId :"
							+ $scope.selectedPSchoolId);
					$scope.schoolid;

					$scope.addPartnerSchool = function() {

						$scope.tabNext();

						$scope.waitForServiceLoad2();
						if ($scope.PaymentDetail.payReceivedBy != "") {
							$scope.PaymentDet.push($scope.PaymentDetail);
							$scope.examDetail.paymentDetail = $scope.PaymentDet;
							$scope.PaymentDetail = {
								payReceivedBy : "",
								paymentDate : new Date(),
								payAmount : 0,
								note : "",
								tPaid : 0,
								pAmount : 0
							}

						}
						$scope.examDetail.bookSummary = $scope.bookSummary;
						$scope.partnerSchool.instituteID = $scope.curUser.instituteID;
						$scope.partnerSchool.contactDetail = $scope.contactDetail;

						if ($scope.schoolid != undefined
								&& $scope.selectedPSchoolId == "") {
							$scope.partnerSchool.id = $scope.schoolid.id;

						}
						/* if ($scope.examlist.length >=1) { */
						$scope.partnerSchool.examDetailList = $scope.examlist;
						/*
						 * } else { $scope.partnerSchool.examDetailList[0] =
						 * $scope.examDetail; }
						 */

						if($scope.partnerSchool.address.state == "Other"){
							$scope.partnerSchool.address.state = $scope.partnerSchool.address.otherState;
							$scope.partnerSchool.address.dist = $scope.partnerSchool.address.otherDist;
							$scope.partnerSchool.address.tal = $scope.partnerSchool.address.otherTaluka;
							$scope.partnerSchool.address.otherAddressFlag = true;
						}else{
							$scope.partnerSchool.address.otherAddressFlag = false;
						}
						var PartnerSchoolService = appEndpointSF
								.getPartnerSchoolService();

						PartnerSchoolService
								.addPartnerSchool($scope.partnerSchool)
								.then(
										function(schoolid) {
											$scope.schoolid = schoolid;
											$scope.partnerSchool.autoGenerated = $scope.schoolid.autoGenerated;
											if ($scope.selectedPSchoolId != undefined) {
												$scope.showUpdateToast();
											} else {
												$scope.showAddToast();
											}

										});
						$scope.waitForServiceLoad2();

					}
					$scope.resetState = function() {
						$state.reload();
					}

					$scope.getPSchoolByPSID = function() {
						var PartnerSchoolService = appEndpointSF
								.getPartnerSchoolService();
						if ($scope.selectedPSchoolId != "") {
							PartnerSchoolService
									.getPSchoolByPSID($scope.selectedPSchoolId)
									.then(
											function(pSchool) {
												$scope.partnerSchool = pSchool;
												$scope.partnerSchool.formNumber = Number($scope.partnerSchool.formNumber);

												$scope.contactDetail = $scope.partnerSchool.contactDetail;
												$scope.partnerSchool.address.pin = Number($scope.partnerSchool.address.pin); 
												$scope.Address = $scope.partnerSchool.address;
												$scope.partnerSchool.address.pin = parseInt($scope.partnerSchool.address.pin);
												
												$scope.partnerSchool.contactDetail.headMasterMobile = parseInt($scope.partnerSchool.contactDetail.headMasterMobile);
												
												for(var i=0; i < $scope.partnerSchool.contactDetail.coordinatorDetail.length; i++){
													$scope.contactDetail.coordinatorDetail.coordinatorMobileNum = parseInt($scope.partnerSchool.contactDetail.coordinatorDetail.coordinatorMobileNum);
												}
												$scope.a;
												$scope.getDistricts($scope.a, $scope.Address.state);
												$scope.getTalukas($scope.a, $scope.Address.dist);
												if ($scope.partnerSchool.examDetailList) {
													$scope.examlist = $scope.partnerSchool.examDetailList;
												}
												if($scope.partnerSchool.address.otherAddressFlag == true){
													var temp = $scope.partnerSchool.address.state;
													$scope.partnerSchool.address.state = "Other";
													$scope.partnerSchool.address.otherState = temp;
													$scope.partnerSchool.address.otherDist = $scope.partnerSchool.address.dist;
													$scope.partnerSchool.address.otherTaluka = $scope.partnerSchool.address.tal;
													$scope.partnerSchool.address.otherAddressFlag = true;
												}
												$scope.getExamByYear();
												$scope.waitForServiceLoad2();
											});
						}

					}

					$scope.examlist = [];

					$scope.waitForServiceLoad = function() {
						if (appEndpointSF.is_service_ready) {
							if ($scope.selectedPSchoolId != undefined) {
								$scope.getPSchoolByPSID();
							}

						} else {
							$log.debug("Services Not Loaded, watiting...");
							$timeout($scope.waitForServiceLoad, 1000);
						}
					}

					$scope.waitForServiceLoad();
					// -----------get Exam by Year------------
					$scope.getExamByYear = function(year1) {
						if (year1 == undefined) {
							var date1 = new Date();
							var year1 = date1.getFullYear();
							year1 = year1.toString().substr(2, 2);
							year1 = date1.getFullYear() + "-"
									+ (Number(year1) + 1);
						}
						var k = 0;
						for (q = 0; q < $scope.examlist.length; q++) {
							if ($scope.examlist[q].yearOfExam == year1) {
								$scope.examDetail = $scope.examlist[q];
								$scope.bookSummary = $scope.examlist[q].bookSummary;
								if ($scope.examlist[q].paymentDetail != undefined) {
									$scope.PaymentDet = $scope.examlist[q].paymentDetail;
								}
								k = 1;
							}

						}
						if (k == 0) {
							$scope.PaymentDet = [];
							$scope.bookSummary = {
								bookDetail : [ {
									standard : "",
									bookName : "",
									bookPrise : 0,
									totalStud : 0,
									totalFees : 0
								} ],
								total : 0,
								amtForInst20per : 0,
								amtForGRF80per : 0
							}
							$scope.examDetail = {
								totalStudent : "",
								male : "",
								female : "",
								total : "",
								/* examMedium : [], */
								yearOfExam : $scope.yearOfExam,
								bookRequired : 'OffLine',
								modeOfExam : 'OffLine',
								bookSummary : $scope.bookSummary,
								paymentDetail : $scope.PaymentDet,
							};

							$scope.examlist.push($scope.examDetail);
							$scope.examDetail = $scope.examlist[$scope.examlist.length - 1];
						}

					}
					$scope.PaymentDet = [];

					$scope.cancelButton = function() {
						$state.go('^', {});
					};

					$scope.back = function() {
						window.history.back();
						// $state.go("^", {});
					};

					$scope.getGFBookStockByInstituteId = function() {
						var gfBookStockService = appEndpointSF
								.getGFBookStockService();
						gfBookStockService.getGFBookByInstituteId(
								$scope.curUser.instituteID).then(
								function(tempBooks) {
									$scope.bookStocks = tempBooks;
								});
					}
					$scope.bookStocks = [];

					$scope.waitForServiceLoad1 = function() {
						if (appEndpointSF.is_service_ready) {

							$scope.getGFBookStockByInstituteId();

						} else {
							$log.debug("Services Not Loaded, watiting...");
							$timeout($scope.waitForServiceLoad1, 1000);
						}
					}

					$scope.waitForServiceLoad1();
					// -----------add book--------------
					$scope.addBook = function() {
						$scope.BookDetail = {
							standard : "",
							bookName : "",
							bookPrise : 0,
							totalStud : 0,
							totalFees : 0
						}
						$scope.bookSummary.bookDetail.push($scope.BookDetail);
					}

					$scope.removeBook = function(index) {
						$scope.calculate(index, 0);
						$scope.bookSummary.bookDetail.splice(index, 1);

					};

					$scope.books = [];

					// -----------------calculate book detail---------------

					$scope.calculate = function(index, val) {

						$scope.bookSummary.bookDetail[index].totalStud = val;

						$scope.bookSummary.bookDetail[index].totalFees = $scope.bookSummary.bookDetail[index].totalStud
								* $scope.bookSummary.bookDetail[index].bookPrise;

						$scope.bookSummary.total = 0;
						for (count = 0; count < $scope.bookSummary.bookDetail.length; count++) {
							$scope.bookSummary.total += $scope.bookSummary.bookDetail[count].totalFees;
						}
						$scope.bookSummary.amtForInst20per = Math
								.round(($scope.bookSummary.total / 100) * 20);
						$scope.bookSummary.amtForGRF80per = Math
								.round(($scope.bookSummary.total / 100) * 80);

						$scope.calculatepaidandpending();
					}

					// -----------add coordinator--------------
					$scope.addCoordinator = function() {
						if($scope.contactDetail.coordinatorDetail == undefined){
							$scope.contactDetail = {
									headMasterName : "",
									headMasterMobile : "",
									headMasterPhone : "",
									headMasterEmailId : "",
									coordinatorDetail : [ {
										srno : 1,
										coordinatorName : "",
										coordinatorPhoneNum : "",
										coordinatorMobileNum : "",
										coordinatorEmailId : "",
									} ]

								}
							$scope.contactDetail.coordinatorDetail;
						
						}else{
							$scope.CoordinatorDetail = {
									srno : $scope.contactDetail.coordinatorDetail.length + 1,
									coordinatorName : "",
									coordinatorPhoneNum : "",
									coordinatorEmailId : "",
								}
								$scope.contactDetail.coordinatorDetail
										.push($scope.CoordinatorDetail);
						}
					}

					$scope.removeCoordinator = function(index) {
						$scope.contactDetail.coordinatorDetail.splice(index, 1);
					};

					// --------calculate pending & total paid amount----

					$scope.calculatepaidandpending = function() {
						// ---------calculate pending amount---------

						$scope.PaymentDetail.tPaid = 0;

						if ($scope.PaymentDet.length != 0) {

							for (i = 0; i < $scope.PaymentDet.length; i++) {

								$scope.PaymentDetail.tPaid += $scope.PaymentDet[i].payAmount;

							}
							$scope.PaymentDetail.tPaid += $scope.PaymentDetail.payAmount;
							$scope.PaymentDetail.pAmount = $scope.bookSummary.amtForGRF80per
									- $scope.PaymentDetail.tPaid;
						} else {

							$scope.PaymentDetail.tPaid = $scope.PaymentDetail.payAmount;
							$scope.PaymentDetail.pAmount = $scope.bookSummary.amtForGRF80per
									- $scope.PaymentDetail.tPaid;
						}

					}

					$scope.PaymentDetailArray = [];

					$scope.waitForServiceLoad2 = function() {
						if (appEndpointSF.is_service_ready) {

							$scope.calculatepaidandpending();

						} else {
							$log.debug("Services Not Loaded, watiting...");
							$timeout($scope.waitForServiceLoad2, 1000);
						}
					}

					$scope.waitForServiceLoad2();

					$scope.setfees = function(id, ind) {

						$log.debug("name=" + angular.toJson(id) + "index="
								+ ind);
						for (i = 0; i < $scope.bookStocks.length; i++) {
							if ($scope.bookStocks[i].id == id) {
								$scope.bookSummary.bookDetail[ind].bookPrise = $scope.bookStocks[i].bookPrice;
							}
						}
						$scope.calculate(ind, 0);
					}
	
									
					$scope.temp = {
							tempDistricts : [],
							tempTalukas : [],
							tempVillages : []
					}
					
					$scope.Address = {
							line1 : "",
							dist : "",
							city : "",
							state : "",
							country : "India",
							pin : "",
							tal : ""
						}
					
					$scope.getDistricts = function(index, state) {
						
						$scope.temp.tempDistricts = [];
						for(var i=0; i < $scope.Country.states.length; i++){
							
							if($scope.Country.states[i].name == state){
							
								$scope.temp.tempDistricts = $scope.Country.states[i].districts;
								
							}
						}
					};
										
					$scope.getTalukas = function(index, district) {
						
						$scope.temp.tempTalukas = [];				
								for(var j=0; j< $scope.temp.tempDistricts.length; j++){
									if($scope.temp.tempDistricts[j].name == district){
									$scope.temp.tempTalukas = $scope.temp.tempDistricts[j].talukas;									
								}	
								}
					};
					
					$scope.getVillages = function(index, taluka) {
						
						$scope.temp.tempVillages = [];				
								for(var k=0; k< $scope.temp.tempTalukas.length; k++){
									if($scope.temp.tempTalukas[k].name == taluka){
									$scope.temp.tempVillages = $scope.temp.tempTalukas[k].villages;									
								}	
								}
					};
					

				$scope.Country = 	{
						states:[{
						name:"Maharashtra", 
							districts:[{name:"Ahmednagar", talukas:[{name:"Akola"},{name:"Sangamner"},
							                                        {name:"Kopargaon"},{name:"Rahta"},
							                                        {name:"Shrirampur"},{name:"Nevasa"},
							                                        {name:"Shevgaon", villages:[{name:"Wagholi"},{name:"Vadule Khurd"},
														                                        {name:"Jalgaon"},{name:"Malegaon"},
														                                        {name:"Samangaon"},{name:"Avhane"},
														                                        {name:"Shevgaon"},{name:"Varur"},
														                                        {name:"Bhagur"},{name:"Bodhegaon"},
														                                        {name:"Hatgaon"},{name:"KamPimpri"},
														                                        {name:"Vadule Budruk"},{name:"Varkhed"}]},
														                                        {name:"Chapadgaon"},
							                                        {name:"Nagar"},{name:"Rahuri"},
							                                        {name:"Parner"},{name:"Pathardi"},{name:"Shrigonda"},
							                                        {name:"Karjat"},{name:"Jamkhed"}]},
							           {name:"Akola", talukas:[{name:"Akola"},{name:"Akot"},
						                                        {name:"Balapur"},{name:"Murtijapur"},
						                                        {name:"Telhara"},{name:"Barshitakli"},
						                                        {name:"Patur"}]},
						               {name:"Amravati", talukas:[{name:"Dharni"},{name:"Chikhaldara"},
							                                        {name:"Anjangaon Surji"},{name:"Achalpur"},
							                                        {name:"Chandurbazar"},{name:"Morshi"},
							                                        {name:"Warud"},{name:"Teosa"},
							                                        {name:"Amravati"},{name:"Bhatkuli"},{name:"Daryapur"},
							                                        {name:"Nandgaon-Khandeshwar"},
							                                        {name:"Chandur Railway"},{name:"Dhamangaon Railway"}]},
							                                      
							           {name:"Aurangabad",talukas:[{name:"Kannad"},{name:"Soegaon"},
							                                        {name:"Sillod"},{name:"Phulambri"},
							                                        {name:"Aurangabad"},{name:"Khuldabad"},
							                                        {name:"Vaijapur"},{name:"Gangapur"},
							                                        {name:"Paithan"}]},
							          
							           {name:"Beed",talukas:[{name:"Ashti"},{name:"Patoda"},
						                                        {name:"Shirur (Kasar)"},{name:"Georai"},
						                                        {name:"Manjlegaon"},{name:"Wadwani"},
						                                        {name:"Bid"},{name:"Kaij"},
						                                        {name:"Dharur"},{name:"Parli"},
						                                        {name:"Ambejogai"}]},
						                                        
						               {name:"Bhandara" ,talukas:[{name:"Bhandara"}]},
						               
						               {name:"Buldhana",talukas:[{name:"Jalgaon (Jamod)"},{name:"Sangrampur"},
							                                        {name:"Shegaon"},{name:"Nandura"},
							                                        {name:"Malkapur"},{name:"Motala"},
							                                        {name:"Khamgaon"},{name:"Mehkar"},
							                                        {name:"Chikhli"},{name:"Buldana"},
							                                        {name:"Deolgaon Raja"},	{name:"Sindkhed Raja"},
							                                        {name:"Lonar"}]},
							                                        
							           {name:"Chandrapur",talukas:[{name:"Warora"},{name:"Chimur"},
							                                        {name:"Nagbhir"},{name:"Brahmapuri"},
							                                        {name:"Sawali"},{name:"Sindewahi"},
							                                        {name:"Bhadravati"},{name:"Chandrapur"},
							                                        {name:"Mul"},{name:"Pombhurna"},
							                                        {name:"Ballarpur"},	{name:"Korpana"},
							                                        {name:"Jiwati"},{name:"Rajura"},{name:"Gondpipri"}]},
							                               							                                        
							           {name:"Dhule",talukas:[{name:"Shirpur"},{name:"Sindkhede"},
						                                        {name:"Sakri"},{name:"Dhule"}]},						                                        
						                                        
							           {name:"Gadchiroli",talukas:[{name:"Desaiganj (Vadasa)"},{name:"Armori"},
							                                        {name:"Kurkheda"},{name:"Korchi"},
							                                        {name:"Dhanora"},{name:"Gadchiroli"},
							                                        {name:"Chamorshi"},{name:"Mulchera"},
							                                        {name:"Etapalli"},{name:"Bhamragad"},
							                                        {name:"Aheri"},	{name:"Sironcha"}]},
							                                        
							           {name:"Gondia",talukas:[{name:"Tirora"},{name:"Goregaon"},
						                                        {name:"Gondiya"},{name:"Amgaon"},
						                                        {name:"Salekasa"},{name:"Sadak-Arjuni"},
						                                        {name:"Arjuni Morgaon"},{name:"Deori"}]},
						                                        
							           {name:"Hingoli", talukas:[{name:"Sengaon"},{name:"Hingoli"},
							                                        {name:"Aundha (Nagnath)"},{name:"Kalamnuri"},
							                                        {name:"Basmath"}]},
							                                        
							           {name:"Jalgaon",talukas:[{name:"Chopda"},{name:"Yawal"},
						                                        {name:"Raver"},{name:"Muktainagar"},
						                                        {name:"Bodvad"},{name:"Bhusawal"},
						                                        {name:"Jalgaon"},{name:"Erandol"},
						                                        {name:"Dharangaon"},{name:"Amalner"},
						                                        {name:"Parola"},	{name:"Bhadgaon"},
						                                        {name:"Chalisgaon"},	{name:"Pachora"},
						                                        {name:"Jamner"}]},
						                                  
						                {name:"Nagpur",talukas:[{name:"Savner"},{name:"Parseoni"},
						                                        {name:"Ramtek"},{name:"Mauda"},
						                                        {name:"Kamptee"},{name:"Nagpur (Rural)"},
						                                        {name:"Nagpur (Urban)"},{name:"Hingna"},
						                                        {name:"Umred"},{name:"Kuhi"},
						                                        {name:"Bhiwapur"},	{name:"Narkhed"},
						                                        {name:"Katol"},	{name:"Kalameshwar"}]},
						                                        
						                {name:"Pune",talukas:[{name:"Junnar"},{name:"Ambegaon"},
						                                        {name:"Shirur"},{name:"Khed"},
						                                        {name:"Mawal"},{name:"Mulshi"},
						                                        {name:"Haveli"},{name:"Pune City"},
						                                        {name:"Daund"},{name:"Purandhar"},
						                                        {name:"Velhe"},	{name:"Bhor"},
						                                        {name:"Baramati"},	{name:"Indapur"}]},
							           
							           {name:"Jalna",talukas:[{name:"Ambad"},{name:"Badnapur"},
						                                        {name:"Bhokardan"},{name:"Ghansawangi"},
						                                        {name:"Jafferabad"},{name:"Jalna"},
						                                        {name:"Mantha"},{name:"Partur"}]},
						               {name:"Kolhapur",talukas:[{name:"Ajra"},{name:"Bavda"},
							                                        {name:"Chandgad"},{name:"Gadhinglaj"},
							                                        {name:"Hatkanangle"},{name:"Kagal"},
							                                        {name:"Karvir"},{name:"Panhala"},
							                                        {name:"Radhanagari"},{name:"Shahuwadi"},
							                                        {name:"Shirol"}]},
							           {name:"Latur",talukas:[{name:"Ahmadpur"},{name:"Ausa"},
						                                        {name:"Chakur"},{name:"Latur"},
						                                        {name:"Nilanga"},{name:"Renapur"},
						                                        {name:"Shirur-Anantpal"},{name:"Udgir"}]},							                                        
							           {name:"Mumbai City"},
							           {name:"Mumbai Suburban",talukas:[{name:"Andheri"},{name:"Borivali"},
								                                        {name:"Kurla"}]},
							        						            
							        	
							           {name:"Nanded",talukas:[{name:"Ardhapur"},{name:"Bhokar"},
						                                        {name:"Biloli"},{name:"Deglur"},
						                                        {name:"Dharmabad"},{name:"Hadgaon"},
						                                        {name:"Himayatnagar"},{name:"Kandhar"},
						                                        
						                                        {name:"Kinwat"},{name:"Loha"},
						                                        {name:"Mahoor"},{name:"Mudkhed"},
						                                        
						                                        {name:"Mukhed"},{name:"Naigaon (Khairgaon)"},
						                                        {name:"Nanded"},{name:"Umri"}]},
							           
							           {name:"Nandurbar",talukas:[{name:"Akkalkuwa"},{name:"Akrani"},
							                                        {name:"Nandurbar"},{name:"Nawapur"},
							                                        {name:"Shahade"},{name:"Talode"}]},
							           {name:"nashik",talukas:[{name:"Baglan"},{name:"Chandvad"},
						                                        {name:"Deola"},{name:"Dindori"},
						                                        {name:"Igatpuri"},{name:"Kalwan"},
						                                        {name:"Malegaon"},{name:"Nandgaon"},
						                                        {name:"Nashik"},{name:"Niphad"},
						                                        {name:"Peint"},{name:"Sinnar"},{name:"Surgana"},
						                                        ,{name:"Trimbakeshwar"},{name:"Yevla"}]},
						               {name:"Osmanabad",talukas:[{name:"Bhum"},{name:"Kalamb"},
							                                        {name:"Lohara"},{name:"Osmanabad"},
							                                        {name:"Paranda"},{name:"Tuljapur"},
							                                        {name:"Umarga"},{name:"Washi"}]},
							           {name:"Parbhani",talukas:[{name:"Gangakhed"},{name:"Jintur"},
							                                        {name:"Manwath"},{name:"Palam"},
							                                        {name:"Parbhani"},{name:"Purna"},
							                                        {name:"Sailu"},{name:"Sonpeth"}]},
							           {name:"Raigad",talukas:[{name:"Alibag"},{name:"Karjat"},
						                                        {name:"Khalapur"},{name:"Mahad"},
						                                        {name:"Mangaon"},{name:"Mhasla"},
						                                        {name:"Murud"},{name:"Panvel"},
						                                        {name:"Pen"},{name:"Poladpur"},
						                                        {name:"Roha"},{name:"Shrivardhan"},
						                                        {name:"Tala"},{name:"Sudhagad"},{name:"Uran"}]},                          
						               {name:"Ratnagiri",talukas:[{name:"Chiplun"},{name:"Dapoli"},
							                                        {name:"Guhagar"},{name:"Khed"},
							                                        {name:"Lanja"},{name:"Mandangad"},
							                                        {name:"Rajapur"},{name:"Ratnagiri"},
							                                        {name:"Sangameshwar"}]},
							           {name:"Sangli",talukas:[{name:"Atpadi"},{name:"Jat"},
						                                        {name:"Kadegaon"},{name:"Kavathemahankal"},
						                                        {name:"Khanapur"},{name:"Miraj"},
						                                        {name:"Palus"},{name:"Shirala"},
						                                        {name:"Tasgaon"},{name:"Walwa"}]},
						               {name:"Satara",talukas:[{name:"Jaoli"},{name:"Karad"},
						                                        {name:"Khandala"},{name:"Khatav"},
						                                        {name:"Koregaon"},{name:"Mahabaleshwar"},
						                                        {name:"Man"},{name:"Patan"},
						                                        {name:"Phaltan"},{name:"Satara"},{name:"Wai"}]},
						               {name:"Sindhudurg",talukas:[{name:"Devgad"},{name:"Dodamarg"},
							                                        {name:"Kankavli"},{name:"Kudal"},
							                                        {name:"Malwan"},{name:"Sawantwadi"},
							                                        {name:"Vaibhavvadi"},{name:"Vengurla"}]},
							           {name:"Solapur",talukas:[{name:"Akkalkot"},{name:"Barshi"},
						                                        {name:"Karmala"},{name:"Madha"},
						                                        {name:"Malshiras"},{name:"Mangalvedhe"},
						                                        {name:"Mohol"},{name:"Pandharpur"},
						                                        {name:"Sangole"},{name:"Solapur North"},
						                                        {name:"Solapur South"}]},
						               {name:"Thane",talukas:[{name:"Ambarnath"},{name:"Bhiwandi"},
						                                        {name:"Dahanu"},{name:"Jawhar"},
						                                        {name:"Kalyan"},{name:"Mokhada"},
						                                        {name:"Murbad"},{name:"Palghar"},
						                                        {name:"Shahapur"},{name:"Talasari"},
						                                        {name:"Thane"},{name:"Ulhasnagar"},{name:"Vada"},
						                                        {name:"Vasai"},{name:"Vikramgad"}]},
							           {name:"Wardha",talukas:[{name:"Arvi"},{name:"Ashti"},
						                                        {name:"Deoli"},{name:"Hinganghat"},
						                                        {name:"Karanja"},{name:"Samudrapur"},
						                                        {name:"Seloo"},{name:"Wardha"}]},
						               {name:"Washim",talukas:[{name:"Karanja"},{name:"Malegaon"},
						                                        {name:"Mangrulpir"},{name:"Manora"},
						                                        {name:"Risod"},{name:"Washim"}]},
						                                        
						               {name:"Yavatmal",talukas:[{name:"Arni"},{name:"Babulgaon"},
							                                        {name:"Darwha"},{name:"Digras"},
							                                        {name:"Ghatanji"},{name:"Kalamb"},
							                                        {name:"Kelapur"},{name:"Mahagaon"},
							                                        {name:"Maregaon"},{name:"Ner"},
							                                        
							                                        {name:"Pusad"},{name:"Ralegaon"},
							                                        {name:"Umarkhed"},{name:"Wani"},
							                                        {name:"Yavatmal"},{name:"Zari-Jamani"}]}
						]},
						{
						name:"Gujarat", 
							districts:[{name:"Ahmedabad",talukas:[{name:"Mandal"},{name:"Detroj-Rampura"},
							                                        {name:"Viramgam"},{name:"Sanand"},
							                                        {name:"Ahmadabad City"},{name:"Daskroi"},
							                                        {name:"Dholka"},{name:"Bavla"},
							                                        {name:"Ranpur"},{name:"Barwala"},
							                                        {name:"Dhandhuka"}]},
							                                     
							          {name:"Amreli",talukas:[{name:"Kunkavav Vadia"},{name:"Babra"},
						                                        {name:"Lathi"},{name:"Lilia"},
						                                        {name:"Amreli"},{name:"Bagasara"},
						                                        {name:"Dhari"},{name:"Savar Kundla"},
						                                        {name:"Khambha"},{name:"Jafrabad"},
						                                        {name:"Rajula"}]},
							                                        
							         {name:"Anand" ,talukas:[{name:"Tarapur"},{name:"Sojitra"},
						                                        {name:"Umreth"},{name:"Anand"},
						                                        {name:"Petlad"},{name:"Khambhat"},
						                                        {name:"Borsad"},{name:"Anklav"}]},
							         
						             {name:"Aravalli",talukas:[{name:"Aravalli"}]},
							         
						             {name:"Banaskantha (Palanpur)",talukas:[{name:"Danta"},{name:"Vadgam"},
										                                        {name:"Palanpur"},{name:"Deesa"},
										                                        {name:"Deodar"},{name:"Bhabhar"},
										                                        {name:"Kankrej"},{name:"Vav"},
										                                        {name:"Tharad"},{name:"Dhanera"},
										                                        {name:"Dantiwada"},{name:"Amirgadh"}]},
										                                        
						            {name:"Bharuch",talukas:[{name:"Jambusar"},{name:"Amod"},
					                                        {name:"Vagra"},{name:"Bharuch"},
					                                        {name:"Jhagadia"},{name:"Anklesvar"},
					                                        {name:"Hansot"},{name:"Valia"}]},
						            
						            {name:"Bhavnagar",talukas:[{name:"Botad"},{name:"Vallabhipur"},
						                                        {name:"Gadhada"},{name:"Umrala"},
						                                        {name:"Bhavnagar"},{name:"Ghogha"},
						                                        {name:"Sihor"},{name:"Gariadhar"},
						                                        {name:"Palitana"},{name:"Talaja"},
						                                        {name:"Mahuva"}]},
						            
						            {name:"Botad",talukas:[{name:"Botad"}]},
						            
						            {name:"Chhota Udepur",talukas:[{name:"Chhota Udepur"}]},
						            
						            {name:"Dahod",talukas:[{name:"Fatepura"},{name:"Jhalod"},
					                                        {name:"Limkheda"},{name:"Dohad"},
					                                        {name:"Garbada"},{name:"Devgadbaria"},
					                                        {name:"Dhanpur"}]},
						            
						            {name:"Dangs (Ahwa)",talukas:[{name:"The Dangs"}]},
						            
						            {name:"Devbhoomi Dwarka"},
						            
						            {name:"Gandhinagar",talukas:[{name:"Kalol"},{name:"Mansa"},
							                                        {name:"Gandhinagar"},{name:"Dehgam"}]},
							                                        
							        {name:"Gir Somnath"},
							        
							        {name:"Jamnagar",talukas:[{name:"Okhamandal"},{name:"Khambhalia"},
						                                        {name:"Jamnagar"},{name:"Jodiya"},
						                                        {name:"Dhrol"},{name:"Kalavad"},
						                                        {name:"Lalpur"},{name:"Kalyanpur"},
						                                        {name:"Bhanvad"},{name:"Jamjodhpur"}]},
							        
							        {name:"Junagadh",talukas:[{name:"Manavadar"},{name:"Vanthali"},
						                                        {name:"Junagadh"},{name:"Bhesan"},
						                                        {name:"Visavadar"},{name:"Mendarda"},
						                                        {name:"Keshod"},{name:"Mangrol"},
						                                        {name:"Malia"},{name:"Talala"},
						                                        {name:"Patan-Veraval"}, {name:"Sutrapada"},
						                                        {name:"Kodinar"},
						                                        {name:"Una"}]},
							        
							        {name:"Kachchh"},{name:"Kheda (Nadiad)"},{name:"Mahisagar"},{name:"Mehsana"},
							           {name:"Morbi"},{name:"Narmada (Rajpipla)"},{name:"Navsari"},{name:"Panchmahal (Godhra)"},
							           {name:"Patan"},{name:"Porbandar"},{name:"Rajkot"},{name:"Sabarkantha (Himmatnagar)"},
							           {name:"Surat"},{name:"Surendranagar"},{name:"Tapi (Vyara)"},{name:"Vadodara"},
							           {name:"Valsad"}]
						},
						{
						name:"Karnataka", 
							districts:[{name:"Bagalkot"},{name:"Bangalore Rural"},{name:"Bangalore Urban"},{name:"Belgaum"},
							           {name:"Bellary"},{name:"Bidar"},{name:"Bijapur"},{name:"Chamarajanagar"},
							           {name:"Chickmagalur"},{name:"Chikballapur"},{name:"Chitradurga"},{name:"Dakshina Kannada"},
							           {name:"Davangere"},{name:"Dharwad"},{name:"Gadag"},{name:"Gulbarga"},
							           {name:"Hassan"},{name:"Haveri"},{name:"Kodagu"},{name:"Kolar"},
							           {name:"Koppal"},{name:"Mandya"},{name:"Mysore"},{name:"Raichur"},
							           {name:"Ramnagara"},{name:"Shimoga"},{name:"Tumkur"},{name:"Udupi"},
							           {name:"Uttara Kannada (Karwar)"},{name:"Yadgir"}]
						},
						{name:"Kerala",
							districts:[{name:"Alappuzha"},{name:"Ernakulam"},{name:"Idukki"},{name:"Kannur"},
							           {name:"Kasaragod"},{name:"Kollam"},{name:"Kottayam"},{name:"Kozhikode"},
							           {name:"Malappuram"},{name:"Palakkad"},{name:"Pathanamthitta"},{name:"Thiruvananthapuram"},
							           {name:"Thrissur"},{name:"Wayanad"}]},
						{name:"Madhya Pradesh", 
							districts:[{name:"Alirajpur"},{name:"Anuppur"},{name:"Ashoknagar"},{name:"Balaghat"},
										{name:"Barwani"},{name:"Betul"},{name:"Bhind"},{name:"Bhopal"},
										{name:"Burhanpur"},{name:"Chhatarpur"},{name:"Chhindwara"},{name:"Damoh"},
										{name:"Datia"},{name:"Dewas"},{name:"Dhar"},{name:"Dindori"},
										{name:"Guna"},{name:"Gwalior"},{name:"Harda"},{name:"Hoshangabad"},
										{name:"Indore"},{name:"Jabalpur"},{name:"Jhabua"},{name:"Katni"},
										{name:"Khandwa"},{name:"Khargone"},{name:"Mandla"},{name:"Mandsaur"},
										{name:"Morena"},{name:"Narsinghpur"},
										{name:"Neemuch"},{name:"Panna"},{name:"Raisen"},{name:"Rajgarh"},
										{name:"Ratlam"},{name:"Rewa"},{name:"Sagar"},{name:"Satna"},
										{name:"Sehore"},{name:"Seoni"},{name:"Shahdol"},{name:"Shajapur"},
										{name:"Sheopur"},{name:"Shivpuri"},{name:"Sidhi"},{name:"Singrauli"},
										{name:"Tikamgarh"},{name:"Ujjain"},{name:"Umaria"},{name:"Vidisha"}]
					    },	
						{name:"Andaman and Nicobar Island",
							districts:[{name:"Nicobar"},{name:"North and Middle Andaman"},{name:"South Andaman"}]
					    },				
						{name:"Andhra Pradesh",
							districts:[{name:"Anantapur"},{name:"Chittoor"},{name:"Cuddapah"},{name:"East Godavari"},
							           {name:"Guntur"},{name:"Krishna"},{name:"Kurnool"},{name:"Nellore"},
							           {name:"Prakasam"},{name:"Srikakulam"},{name:"Visakhapatnam"},{name:"Vizianagaram"},
							           {name:"West Godavari"}]
					    },
						{name:"Chandigarh",
							districts:[{name:"Chandigarh"}]
					    },
						{name:"Dadra and Nagar Haveli",
							districts:[{name:"Dadra and Nagar Haveli"}]
						},
						{name:"Daman and Diu",
							districts:[{name:"Daman"},{name:"Diu"}]
						},
						{name:"Delhi",
							districts:[{name:"Central Delhi"},{name:"East Delhi"},{name:"New Delhi"},{name:"North Delhi"},
							           {name:"North East Delhi"},{name:"North West Delhi"},{name:"South Delhi"},
							           {name:"South West Delhi"}]
						},
						{name:"Goa",
							districts:[{name:"North Goa"},{name:"South Goa"}]
						},
						{name:"Arunachal Pradesh"},
						{name:"Assam"},
						{name:"Bihar"},
						{name:"Chhattisgarh"},
						
						{name:"Haryana"},
						{name:"Himachal Pradesh"},
						{name:"Jammu and Kashmir"},
						{name:"Jharkhand"},
						{name:"Manipur"},
						{name:"Meghalaya"},
						{name:"Mizoram"},
						{name:"Nagaland"},
						{name:"Orissa"},
						{name:"Punjab"},
						{name:"Pondicherry"},
						{name:"Rajasthan"},
						{name:"Sikkim"},
						{name:"Tamil Nadu"},
						{name:"Tripura"},
						{name:"Uttar Pradesh"},
						{name:"Uttarakhand"},
						{name:"West Bengal"}	,
						{name:"Other"}
						]
				}
	
				$scope.getaddress = function(postcode){
					
					 $.getJSON('https://maps.googleapis.com/maps/api/geocode/json?address=' + postcode + '&sensor=false', function(data) {

						 $scope.data = data.results[0].address_components;
						 var city = $scope.data[1].long_name;
						 var tal = $scope.data[1].long_name;
						 var dist = $scope.data[2].long_name;
						 var state = $scope.data[3].long_name;
						 var country = $scope.data[4].long_name;
						 
						 $scope.partnerSchool.address.city = city;
						 $scope.partnerSchool.address.tal = tal;
						 $scope.partnerSchool.address.dist = dist;
						 $scope.partnerSchool.address.state = state;
						 $scope.partnerSchool.address.country = country;
						 $scope.partnerSchool.address.pin = postcode;
						 
						 $scope.getTalukas(0, dist);
	/*					    var lat = data.results[0].geometry.location.lat;
						    var lng = data.results[0].geometry.location.lng;
	*/			});
				}
				
				$scope.stateQuerySearch = function(query) {
					var results = query ? $scope.Country.states
							.filter(createFilterFor(query))
							: $scope.Country.states;
							$scope.partnerSchool.address.dist = results[0].districts;
					var deferred = $q.defer();
					$timeout(function() {
						deferred.resolve(results);
						
					}, Math.random() * 1000, false);
					
					
					return deferred.promise;
				}
				
				function createFilterFor(query) {
					var lowercaseQuery = angular.lowercase(query);
					return function filterFn(state) {
						var a = state.name;
						return (angular.lowercase(a).indexOf(
								lowercaseQuery) >= 0);
					};
				}
/*
				$scope.DistQuerySearch = function(query) {
					var results = query ? $scope.partnerSchool.address.dist
							.filter(createFilterFor(query))
							: $scope.partnerSchool.address.dist;
							$scope.partnerSchool.address.tal = results.talukas;
					var deferred = $q.defer();
					$timeout(function() {
						deferred.resolve(results);
						
					}, Math.random() * 1000, false);
					
					
					return deferred.promise;
				}
				
				function createFilterFor(query) {
					var lowercaseQuery = angular.lowercase(query);
					return function filterFn(taluka) {
						var a = taluka.name;
						return (angular.lowercase(a).indexOf(
								lowercaseQuery) >= 0);
					};
				}
*/				
				});
